#one-it team project configuration
server:
  port: 8080
  servlet:
    context-path: /one-it-api
  error:
    include-exception: true #응답에 exception의 내용을 포함할지 여부

spring: 
  application:
    name: one-it-api
  datasource:
    url: jdbc:mariadb://oneit-mariadb.cqrt0t8e1rsq.ap-northeast-2.rds.amazonaws.com/oneit
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: oneit3020  
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false    # hibernate가 db에 날리는 쿼리 보여줌
        format_sql: true  # 쿼리 보기 좋게 줄바꿈 등 해줌
        use_sql_comments: true   # 쿼리에 추가적인 주석을 표시해줌
  
      