#one-it team project configuration
server:
  port: 8080
  servlet:
    context-path: /one-it-api
  error:
    include-exception: true #응답에 exception의 내용을 포함할지 여부

spring: 
  datasource:
    #jdbc:mariadb://oneit-mariadb.cqrt0t8e1rsq.ap-northeast-2.rds.amazonaws.com:3306/oneit
    url: jdbc:mysql://localhost:3306/oneit
    #org.mariadb.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #oneit3020
    username: root
    password: pansunluv!2ayeon
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
  
jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400   