#one-it team project configuration
server:
  port: 8080
  servlet:
    context-path: /one-it-api
  error:
    include-exception: true #응답에 exception의 내용을 포함할지 여부

spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/oneit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pansunluv!2ayeon
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
  
jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400   
  
  
  
  #private static final long REFRESH_TOKEN_EXPIRE_TIME = 24 * 60 * 60 * 1000L;// 1일
  #private static final long ACCESS_TOKEN_EXPIRE_TIME = 12 * 60 * 60 * 1000L;// 20분
  